image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - docker-compose up --build 
  - sleep 30
  - java -jar aqa-shop.jar &
  - sleep 30

build_script:
  - chmod +x gradlew
  - ./gradlew test "-Durl.database=jdbc:postgresql://localhost:5432/app" "-Dlogin.database=app" "-Dpassword.database=pass"  # запускаем тест, флаг --info позволяет выводить больше информации
